feature/task internal utils
ozoncp/ocp-response-api pull request #2
Opened 2021-07-16 13:39 UTC by gevorg96

2021-07-18 21:19 UTC, dk13danger requested changes

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +package utils
Давай положим это в отдельную папку - `utils`. Так принято в Го пакет == имя папки

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +func ChunkByte(slice []byte, chunkSize int) [][]byte {
В задаче просят сделать пока 2 типа: `int` и `string`. Давай сейчас реализуем только эти функции

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +		chunks[i/chunkSize] = append(chunks[i/chunkSize], slice[i])
Красиво, молодец!

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +package utils
Добавь сюда тесты. Всегда нужно писать юнит-тесты для пакетов

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +	bufferSize := l / chunkSize
Что если `chunkSize == 0` ?

2021-07-18 21:19 UTC, dk13danger commented on internal/chunk.go
> +func ChunkInt(slice []int, chunkSize int) [][]int {
Каждая экспортируемая функция должна иметь комментарий. Коротко: что делает

2021-07-18 21:19 UTC, dk13danger commented on internal/filters.go
> +func FilterInt(slice []int, f func(int) bool) []int {
Давай назовем `filterFunc`, чтобы было понятно

2021-07-18 21:19 UTC, dk13danger commented on internal/reverse_map.go
> +func ReverseIntInterface(dict map[int]interface{}) map[interface{}]int {
Как я говорил выше - давай оставим только функции с `int` и `string` (4 штуки будет)

2021-07-18 22:52 UTC, gevorg96 commented on internal/chunk.go
> +package utils
положил в другую папку + сделал тесты

2021-07-18 22:52 UTC, gevorg96 commented on internal/chunk.go
> +	bufferSize := l / chunkSize
будет ошибка, там в методе validate проверяется

2021-07-18 23:08 UTC, gevorg96 commented on internal/chunk.go
> +		chunks[i/chunkSize] = append(chunks[i/chunkSize], slice[i])
спасибо)

2021-07-18 23:08 UTC, gevorg96 commented on internal/chunk.go
> +func ChunkByte(slice []byte, chunkSize int) [][]byte {
убрал лишнее

2021-07-18 23:08 UTC, gevorg96 commented on internal/chunk.go
> +func ChunkInt(slice []int, chunkSize int) [][]int {
что мог, выдумал)

2021-07-18 23:08 UTC, gevorg96 commented on internal/filters.go
> +func FilterInt(slice []int, f func(int) bool) []int {
++

2021-07-18 23:08 UTC, gevorg96 commented on internal/reverse_map.go
> +func ReverseIntInterface(dict map[int]interface{}) map[interface{}]int {
убрал лишнее

2021-07-19 20:48 UTC, dk13danger approved these changes

2021-07-19 20:49 UTC, merged