task-3
ozoncp/ocp-response-api pull request #3
Opened 2021-07-20 23:33 UTC by gevorg96

2021-07-23 09:37 UTC, dk13danger requested changes

2021-07-23 09:37 UTC, dk13danger commented on domain/response.go
> +func NewResponse(id uint64, userId uint64, requestId uint64, text string) *Response {
Это лишний конструктор. Не усложняй код: передать параметры, чтобы просто создать структуру и вернуть ее назад слишком простая операция

2021-07-23 09:37 UTC, dk13danger commented on domain/response.go
> +	return fmt.Sprintf("Id: %d, UserId: %d, RequestId: %d, Text: %s", r.Id, r.UserId, r.RequestId, r.Text)
На самом деле, можно гораздо проще: `fmt.Sprintf("%#v", r)`

2021-07-23 09:37 UTC, dk13danger commented on internal/tests/chunks_test.go
> +	"github.com/ozoncp/ocp-response-api/domain"
Импорты принято разделать пустыми строками так:
```
// std lib (fmt, net, reflect, etc..)

// 3rd-party libs (github, golang.org, etc..)

// your project internal packages
```

Поправь во всем проекте

2021-07-23 09:37 UTC, dk13danger commented on internal/tests/chunks_test.go
> +func TestChunk4From10(t *testing.T) {
Обычно тесты так не пишут. Каждая "тест функция" - это отдельная проверка на сущность операции. Например:
- проверить, что возвращается правильный ответ
- проверить, что возвращется ошибка
- проверить, что возвращается nil
- и т.д.

Один функционал теста (например, проверку на правильную логику работы функции) принято делать сразу несколькими тестовыми данными прямо в одной функции. Например (взял из моего тестового проекта - просто пример)
```
func TestExample(t *testing.T) {
	tests := []struct {
		slice     []int
		chunkSize int
		want      [][]int
	}{
		{
			[]int{1},
			3,
			[][]int{{1}},
		},
		{
			[]int{1, 2, 3},
			3,
			[][]int{{1, 2, 3}},
		},
		{
			[]int{1, 2, 3, 4, 5},
			2,
			[][]int{{1, 2}, {3, 4}, {5}},
		},
	}

	for _, tt := range tests {
		t.Run("", func(t *testing.T) {
			actual := chunkSliceInt(tt.slice, tt.chunkSize)
			assert.ElementsMatch(t, actual, tt.want)
		})
	}
}
```

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/errors.go
> +const ChunkSizeLEqualZeroError = "Chunk size must be greater than 0"
Константы для ошибок не заводят (я такого, по крайней мере не видел)
Заводят перменные:
`var errSuper = errors.New("Super error")`

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/chunks.go
> +		return errors.New(ChunkSizeLEqualZeroError)
Выделенная ошибка не нужна. Снаружи неважно что именно случилось при валидации - важно прокинуть ошибку выше, просто обернув ее своим текстом (это принцип Го).

Это не будет и не должно влиять на код "вызывающего кода" и внешней бизнес-логики.

Я бы просто вернул так:
`fmt.Errorf("error while validating input params: chunkSize must be more zero, chunkSize: [%d]", chunkSize)`

Инфо: в пакете sql возвращается ошибка `sql.NoRows` (точно название не вспомню и нет времени гуглить). Так вот тут ошибка явно влияет на логику внешнего вызова, т.к. в зависимости от наличия/отсутствия строк код выше может НЕ вывести ошибку дальше, например, а просто показать текст

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/chunks.go
> +// ChunkString Makes chunks from slice of strings
"Makes" с маленькой буквы (везде с маленкой начало коммента)

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/converters.go
> +	dict := make(map[uint64]domain.Response)
Давай для мапы зададим длину, чтобы не аллоцировать память постоянно. Это дорого.

Кстати, тут скажу: твое решение по нарезке чанков очень красивое, но, конечно, не оптимальное по памяти, т.к. там используется append и постоянно перезаисываются слайсы. Если напишешь бенчмарк - то увидишь это

Конечно, лучше (с точки зрения оптимизации кода) "нарезать" слайс прямо на месте, тако конструкцией: slice[x:y]. В этом случае у тебя будут операции с указателями, но код станет грязнее.

_Если интересно - в личку потом накатаю пример и скину (о чем я говорю вообще)_

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/converters.go
> +	dict := make(map[uint64]domain.Response)
Обычно я все, что возвращаю называю res, чтобы потом в коде были в достатке "самые юзабельные" имена + чтобы всегда в середине функции понимать, что это конечный результат. (просто делюсь опытом)

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/converters.go
> +	for _, v := range entities {
Давай так: v == entity. Все должно быть информативно (понятно, что тут три строки кода, но все же - это хороший тон)

2021-07-23 09:37 UTC, dk13danger commented on domain/response.go
> +package domain
Раз мы делаем все "внутри проекта" - это тоже положи в `utils`

JFYI:
https://github.com/golang-standards/project-layout

2021-07-23 09:37 UTC, dk13danger commented on internal/tests/chunks_test.go
> +package tests
Обычно юнит-тесты кладут прямо рядом с файлом, который тестится, прямо в тот же пакет

В такую "отдельную" папку test кладут функциональные/интеграционные тесты

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/files.go
> +
Пустую строку убери

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/files.go
> +	readFile := func() (content string, err error) {
Давай не будем использовать именованные переменные для возврата (это только с толку сбивает, поверь)

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/files.go
> +			return "", nil
Тут ошибку надо вернуть

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/files.go
> +	for i = 0; i < iter; i++ {
Давай просто:
`for i := 0; i < iter; i++ {`

`Iter` сделай просто `int`, добавь проверку на `<= 0`

2021-07-23 09:37 UTC, dk13danger commented on internal/utils/files.go
> +			return nil, err
Если err - то не надо останавливаться. Надо все "попытки испробовать". Плюс, я бы добавли задержку, например 1s между попытками, а не пробовал бы открыть файл напролом.

Конечную ошибку, конечно, нужно показывать и возвращать (если все попытки провалились)

2021-07-23 14:38 UTC, gevorg96 commented on domain/response.go
> +func NewResponse(id uint64, userId uint64, requestId uint64, text string) *Response {
убрал

2021-07-23 14:38 UTC, gevorg96 commented on domain/response.go
> +	return fmt.Sprintf("Id: %d, UserId: %d, RequestId: %d, Text: %s", r.Id, r.UserId, r.RequestId, r.Text)
++

2021-07-23 14:38 UTC, gevorg96 commented on internal/tests/chunks_test.go
> +	"github.com/ozoncp/ocp-response-api/domain"
++

2021-07-23 14:38 UTC, gevorg96 commented on internal/tests/chunks_test.go
> +func TestChunk4From10(t *testing.T) {
переделал все тесты на тест-кейсы

2021-07-23 14:39 UTC, gevorg96 commented on internal/utils/errors.go
> +const ChunkSizeLEqualZeroError = "Chunk size must be greater than 0"
я видел, но убрал вообще файл с ошибками

2021-07-23 14:39 UTC, gevorg96 commented on internal/utils/chunks.go
> +		return errors.New(ChunkSizeLEqualZeroError)
возвращаю fmt.Errorf("*")

2021-07-23 14:39 UTC, gevorg96 commented on internal/utils/chunks.go
> +// ChunkString Makes chunks from slice of strings
++

2021-07-23 14:40 UTC, gevorg96 commented on internal/utils/converters.go
> +	dict := make(map[uint64]domain.Response)
я изначально так и делал, но потом "грязное" решение не понравилось, но что поделать
жертвуем простотой ради производительности

2021-07-23 14:40 UTC, gevorg96 commented on internal/utils/converters.go
> +	for _, v := range entities {
++

2021-07-23 14:41 UTC, gevorg96 commented on domain/response.go
> +package domain
++

2021-07-23 14:41 UTC, gevorg96 commented on internal/tests/chunks_test.go
> +package tests
++

2021-07-23 14:41 UTC, gevorg96 commented on internal/utils/files.go
> +
++

2021-07-23 14:41 UTC, gevorg96 commented on internal/utils/files.go
> +	readFile := func() (content string, err error) {
++

2021-07-23 14:41 UTC, gevorg96 commented on internal/utils/files.go
> +			return "", nil
++

2021-07-23 14:41 UTC, gevorg96 commented on internal/utils/files.go
> +	for i = 0; i < iter; i++ {
++

2021-07-23 14:42 UTC, gevorg96 commented on internal/utils/files.go
> +			return nil, err
добавил задержку и прихранивание промежуточных ошибок

2021-07-23 15:04 UTC, gevorg96 commented on internal/utils/reverse_map.go
> +		if _, ok := reverseDict[v]; ok {
Добавил ещё сюда проверку, а то дубликаты не учитывал

2021-07-26 11:15 UTC, dk13danger commented on internal/utils/reverse_map.go
> +		if _, ok := reverseDict[v]; ok {
Ну, по идее, это не страшно) Проверка лишняя - у тебя просто ключ в мапе перезапишется и все

```
myMap[1] = "yes"
myMap[1] = "no"

fmt.Println(myMap[1]) // "no"
```

Но, оставь, это просто FYI

2021-07-26 11:16 UTC, dk13danger approved these changes

2021-07-26 11:16 UTC, merged