Task-4 Flusher Repo
ozoncp/ocp-response-api pull request #4
Opened 2021-07-30 00:09 UTC by gevorg96

2021-08-02 13:05 UTC, dk13danger requested changes

2021-08-02 13:05 UTC, dk13danger commented on internal/flusher/flusher.go
> +	responseRepo repo.ResponseRepo
Интерфейс должен называться Repo (по заданию)

2021-08-02 13:05 UTC, dk13danger commented on internal/flusher/flusher.go
> +		panic(err)
Ну нет. Я бы панику не вызывал. Это не путь Го (точно не в таких методах). 

Кроме того, не даром же flush возвращает массив (по заданию). Даже без ошибки. Я не автор задания, но думаю, что тут речь про то, что метод "флюш" сколько может столько и скидывает в хранилище и возвращает результат наружу. А уже проверить что все записано и вызвать еще раз - это задача вышестоящей бизнес-логики.

Надо использовать твою нарезку на чанки и переписать реализацию метода

2021-08-02 13:05 UTC, dk13danger commented on internal/utils/chunks.go
> +	"github.com/ozoncp/ocp-response-api/internal/models"
Пробел. В IDE Goland (если ты ей пользуешься, конечно) есть специальный хоткей для этого: `CTRL+SHIFT+ALT+I`

2021-08-02 14:24 UTC, gevorg96 commented on internal/flusher/flusher.go
> +	responseRepo repo.ResponseRepo
++

2021-08-02 14:24 UTC, gevorg96 commented on internal/flusher/flusher.go
> +		panic(err)
++

2021-08-02 14:25 UTC, gevorg96 commented on internal/utils/chunks.go
> +	"github.com/ozoncp/ocp-response-api/internal/models"
++

2021-08-02 14:53 UTC, dk13danger requested changes

2021-08-02 14:53 UTC, dk13danger commented on internal/utils/converters_test.go
> +
Тут пробел не нужен

2021-08-02 14:53 UTC, dk13danger commented on internal/flusher/flusher.go
> +			_ = f.repo.AddResponses(chunk)
Не. Тебе надо добавить все, что сможешь и вернуть это наверх.

Пример:
тебе прилетает 10 сущностей. Ты разбил на чанки по 2. Итого 5 чанков. Добавилось только 2 и 4 чанк, остальные упали с ошибкой. В ответе функции Flush ты отправляешь сущности: 3,4 (2 чанк) и 7,8 (4 чанк)

2021-08-02 14:59 UTC, gevorg96 commented on internal/utils/converters_test.go
> +
почему? это же third-party lib, а ниже мой пакет.
Ты вроде так говорил делать

2021-08-02 16:01 UTC, gevorg96 commented on internal/flusher/flusher.go
> +			_ = f.repo.AddResponses(chunk)
готово

2021-08-03 21:17 UTC, dk13danger commented on internal/utils/converters_test.go
> +
Да, ты прав, сорри (привык все что гитхаб - это стороннее - у нас гитлаб на работе)))

2021-08-03 21:18 UTC, dk13danger approved these changes

2021-08-03 21:18 UTC, merged